[package]
description = "Serializers"
edition = "2021"
name = "ser"
version = "0.0.1"

[lib]
bench = false
name = "ser"

[dependencies]
ser_raw = { version = "0.0.1", path = "../../../../crates/ser_raw/ser_raw" }
swc_atoms = { version = "0.2.13", path = "../swc_atoms" }
